version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: api
    volumes:
      - ./postgres_storage:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - 8080:5000